# Generated by Django 5.0.3 on 2024-06-20 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=60)),
                ('direccionResidencia', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=150)),
                ('tipoUsuario', models.IntegerField(choices=[(1, 'Lector'), (2, 'Bibliotecario'), (3, 'Administrador')])),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_ejem_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_ejem_ocupados',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado_prestamo', models.IntegerField(choices=[(1, 'Préstamo'), (2, 'Entregado'), (3, 'Cancelado')])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='libreria.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='libreria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_multa', models.IntegerField()),
                ('fecha_multa', models.DateField()),
                ('estado_multa', models.IntegerField(choices=[(1, 'Pagada'), (2, 'Pendiente')])),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='libreria.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multa', to='libreria.usuario')),
            ],
        ),
    ]
