# Generated by Django 5.0.3 on 2024-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_usuario_alter_libro_num_ejem_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[(1, 'Lector'), (2, 'Bibliotecario'), (3, 'Administrador')], max_length=20),
        ),
    ]
