# Generated by Django 5.0.3 on 2024-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Lector'), (2, 'Bibliotecario'), (3, 'Administrador')], default=1),
        ),
    ]
