# Generated by Django 5.0.3 on 2024-06-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_remove_usuario_tipousuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Lector', 'Lector'), ('Bibliotecario', 'Bibliotecario'), ('Administrador', 'Administrador')], max_length=20),
        ),
    ]
