# Generated by Django 5.0.3 on 2024-06-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_multa_estado_multa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Prestamo', 'Prestamo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
